[project]
name = "n-gram-generation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sofia", email = "sofasinitsina@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "pandas>=3.0.6",
    "reflex>=0.9.11.post1",
]

[build-system]
requires = ["uv_build>=0.12.16,<0.13.0"]
build-backend = "uv_build"
